#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Carp-Assert
version:      0.18
version_from: lib/Carp/Assert.pm
installdirs:  site
requires:
    Carp:                          0
    Test::More:                    0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
